--
-- PostgreSQL database dump
--

\restrict QUy3rPIJKXtL2HsMDmfOHSg0HP8f1es6C7XQNII0PCrjXH7X9syo09cpSNQJhep

-- Dumped from database version 16.11 (Debian 16.11-1.pgdg13+1)
-- Dumped by pg_dump version 16.11 (Debian 16.11-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: attachment; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.attachment (
    id integer NOT NULL,
    parent_attachment_id integer,
    uploaded_by integer NOT NULL,
    resolution_id integer,
    filename character varying,
    relative_path character varying,
    uploaded_at timestamp without time zone DEFAULT now(),
    presentmon_file boolean,
    presentmon_version character varying,
    settings json
);


ALTER TABLE public.attachment OWNER TO admin;

--
-- Name: attachment_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.attachment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.attachment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: client; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.client (
    id integer NOT NULL,
    name character varying
);


ALTER TABLE public.client OWNER TO admin;

--
-- Name: client_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.client ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.client_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: device; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.device (
    id integer NOT NULL,
    project_id integer NOT NULL,
    name_external character varying,
    name_internal character varying,
    cpu character varying,
    gpu character varying,
    ram character varying
);


ALTER TABLE public.device OWNER TO admin;

--
-- Name: device_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.device ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.device_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: execution; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.execution (
    id integer NOT NULL,
    device_id integer NOT NULL,
    run_id integer NOT NULL,
    test_case_version_id integer NOT NULL,
    executed_by integer NOT NULL,
    status_id integer NOT NULL,
    attachment_id integer,
    actual_result text,
    executed_at timestamp without time zone,
    execution_order integer NOT NULL
);


ALTER TABLE public.execution OWNER TO admin;

--
-- Name: execution_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.execution ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.execution_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: project; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.project (
    id integer NOT NULL,
    name character varying,
    client_id integer NOT NULL
);


ALTER TABLE public.project OWNER TO admin;

--
-- Name: project_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.project ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.project_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: resolution; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.resolution (
    id integer NOT NULL,
    h integer NOT NULL,
    w integer NOT NULL
);


ALTER TABLE public.resolution OWNER TO admin;

--
-- Name: resolution_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.resolution ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.resolution_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: run; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.run (
    id integer NOT NULL,
    name character varying,
    started_at timestamp without time zone,
    done_at timestamp without time zone,
    test_suite_metadata text,
    project_id integer NOT NULL
);


ALTER TABLE public.run OWNER TO admin;

--
-- Name: run_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.run ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.run_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: scenario; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.scenario (
    id integer NOT NULL,
    name character varying
);


ALTER TABLE public.scenario OWNER TO admin;

--
-- Name: scenario_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.scenario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.scenario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: status; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.status (
    id integer NOT NULL,
    status_set_id integer NOT NULL,
    name character varying NOT NULL,
    description text
);


ALTER TABLE public.status OWNER TO admin;

--
-- Name: status_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.status ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.status_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: status_set; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.status_set (
    id integer NOT NULL,
    name character varying
);


ALTER TABLE public.status_set OWNER TO admin;

--
-- Name: status_set_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.status_set ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.status_set_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: suitcase; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.suitcase (
    id integer NOT NULL,
    test_case_id integer NOT NULL,
    test_suite_id integer NOT NULL
);


ALTER TABLE public.suitcase OWNER TO admin;

--
-- Name: suitcase_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.suitcase ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.suitcase_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: test_case; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.test_case (
    id integer NOT NULL,
    scenario_id integer NOT NULL,
    status_set_id integer NOT NULL
);


ALTER TABLE public.test_case OWNER TO admin;

--
-- Name: test_case_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.test_case ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.test_case_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: test_case_version; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.test_case_version (
    id integer NOT NULL,
    test_case_id integer NOT NULL,
    created_by integer NOT NULL,
    release_ready boolean DEFAULT false,
    version integer NOT NULL,
    name character varying,
    description text,
    steps text,
    expected_result text,
    created_at timestamp without time zone DEFAULT now()
);


ALTER TABLE public.test_case_version OWNER TO admin;

--
-- Name: test_case_version_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.test_case_version ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.test_case_version_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: test_suite; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.test_suite (
    id integer NOT NULL,
    name character varying
);


ALTER TABLE public.test_suite OWNER TO admin;

--
-- Name: test_suite_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.test_suite ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.test_suite_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."user" (
    id integer NOT NULL,
    user_group_id integer,
    user_type_id integer NOT NULL,
    first_name character varying NOT NULL,
    last_name character varying NOT NULL,
    email character varying NOT NULL,
    password character varying NOT NULL,
    active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT now(),
    last_login_at timestamp without time zone
);


ALTER TABLE public."user" OWNER TO admin;

--
-- Name: user_group; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.user_group (
    id integer NOT NULL,
    created_by_id integer NOT NULL,
    owner_id integer NOT NULL,
    name character varying
);


ALTER TABLE public.user_group OWNER TO admin;

--
-- Name: user_group_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.user_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public."user" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_type; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.user_type (
    id integer NOT NULL,
    name character varying NOT NULL,
    description text
);


ALTER TABLE public.user_type OWNER TO admin;

--
-- Name: user_type_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.user_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: attachment; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.attachment (id, parent_attachment_id, uploaded_by, resolution_id, filename, relative_path, uploaded_at, presentmon_file, presentmon_version, settings) FROM stdin;
\.


--
-- Data for Name: client; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.client (id, name) FROM stdin;
\.


--
-- Data for Name: device; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.device (id, project_id, name_external, name_internal, cpu, gpu, ram) FROM stdin;
\.


--
-- Data for Name: execution; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.execution (id, device_id, run_id, test_case_version_id, executed_by, status_id, attachment_id, actual_result, executed_at, execution_order) FROM stdin;
\.


--
-- Data for Name: project; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.project (id, name, client_id) FROM stdin;
\.


--
-- Data for Name: resolution; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.resolution (id, h, w) FROM stdin;
\.


--
-- Data for Name: run; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.run (id, name, started_at, done_at, test_suite_metadata, project_id) FROM stdin;
\.


--
-- Data for Name: scenario; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.scenario (id, name) FROM stdin;
\.


--
-- Data for Name: status; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.status (id, status_set_id, name, description) FROM stdin;
\.


--
-- Data for Name: status_set; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.status_set (id, name) FROM stdin;
\.


--
-- Data for Name: suitcase; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.suitcase (id, test_case_id, test_suite_id) FROM stdin;
\.


--
-- Data for Name: test_case; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.test_case (id, scenario_id, status_set_id) FROM stdin;
\.


--
-- Data for Name: test_case_version; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.test_case_version (id, test_case_id, created_by, release_ready, version, name, description, steps, expected_result, created_at) FROM stdin;
\.


--
-- Data for Name: test_suite; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.test_suite (id, name) FROM stdin;
\.


--
-- Data for Name: user; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public."user" (id, user_group_id, user_type_id, first_name, last_name, email, password, active, created_at, last_login_at) FROM stdin;
2	\N	2	root	root	admin@test.com	JDJiJDEyJGJsTzdKLkFuS0E2WVVRSVZHZ3JPMU8uLzB6M1QvTHhjMldDeWswc2N2UnFjZGNYL3RxendL	t	2026-01-12 16:51:40.326101	\N
4	\N	1	Ann	smith	ann@mail.com	JDJiJDEyJE0wcVFqeVdwS3dKbTRQQ1lCWEd2RWU2c3RZYUpEV01yYkNIQTNOV2lTUFNkTi5NVzZxanou	t	2026-01-12 17:43:07.776632	\N
\.


--
-- Data for Name: user_group; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.user_group (id, created_by_id, owner_id, name) FROM stdin;
\.


--
-- Data for Name: user_type; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.user_type (id, name, description) FROM stdin;
1	regular	Default regular user
2	admin	Administrator
\.


--
-- Name: attachment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.attachment_id_seq', 1, false);


--
-- Name: client_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.client_id_seq', 1, false);


--
-- Name: device_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.device_id_seq', 1, false);


--
-- Name: execution_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.execution_id_seq', 1, false);


--
-- Name: project_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.project_id_seq', 1, false);


--
-- Name: resolution_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.resolution_id_seq', 1, false);


--
-- Name: run_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.run_id_seq', 1, false);


--
-- Name: scenario_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.scenario_id_seq', 1, false);


--
-- Name: status_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.status_id_seq', 1, false);


--
-- Name: status_set_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.status_set_id_seq', 1, false);


--
-- Name: suitcase_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.suitcase_id_seq', 1, false);


--
-- Name: test_case_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.test_case_id_seq', 1, false);


--
-- Name: test_case_version_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.test_case_version_id_seq', 1, false);


--
-- Name: test_suite_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.test_suite_id_seq', 1, false);


--
-- Name: user_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.user_group_id_seq', 1, false);


--
-- Name: user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.user_id_seq', 20, true);


--
-- Name: user_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.user_type_id_seq', 176, true);


--
-- Name: attachment attachment_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.attachment
    ADD CONSTRAINT attachment_pkey PRIMARY KEY (id);


--
-- Name: client client_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.client
    ADD CONSTRAINT client_pkey PRIMARY KEY (id);


--
-- Name: device device_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.device
    ADD CONSTRAINT device_pkey PRIMARY KEY (id);


--
-- Name: execution execution_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.execution
    ADD CONSTRAINT execution_pkey PRIMARY KEY (id);


--
-- Name: project project_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.project
    ADD CONSTRAINT project_pkey PRIMARY KEY (id);


--
-- Name: resolution resolution_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.resolution
    ADD CONSTRAINT resolution_pkey PRIMARY KEY (id);


--
-- Name: run run_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.run
    ADD CONSTRAINT run_pkey PRIMARY KEY (id);


--
-- Name: scenario scenario_name_key; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.scenario
    ADD CONSTRAINT scenario_name_key UNIQUE (name);


--
-- Name: scenario scenario_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.scenario
    ADD CONSTRAINT scenario_pkey PRIMARY KEY (id);


--
-- Name: status status_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.status
    ADD CONSTRAINT status_pkey PRIMARY KEY (id);


--
-- Name: status_set status_set_name_key; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.status_set
    ADD CONSTRAINT status_set_name_key UNIQUE (name);


--
-- Name: status_set status_set_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.status_set
    ADD CONSTRAINT status_set_pkey PRIMARY KEY (id);


--
-- Name: suitcase suitcase_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.suitcase
    ADD CONSTRAINT suitcase_pkey PRIMARY KEY (id);


--
-- Name: test_case test_case_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.test_case
    ADD CONSTRAINT test_case_pkey PRIMARY KEY (id);


--
-- Name: test_case_version test_case_version_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.test_case_version
    ADD CONSTRAINT test_case_version_pkey PRIMARY KEY (id);


--
-- Name: test_suite test_suite_name_key; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.test_suite
    ADD CONSTRAINT test_suite_name_key UNIQUE (name);


--
-- Name: test_suite test_suite_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.test_suite
    ADD CONSTRAINT test_suite_pkey PRIMARY KEY (id);


--
-- Name: user_group user_group_name_key; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.user_group
    ADD CONSTRAINT user_group_name_key UNIQUE (name);


--
-- Name: user_group user_group_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.user_group
    ADD CONSTRAINT user_group_pkey PRIMARY KEY (id);


--
-- Name: user user_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_pkey PRIMARY KEY (id);


--
-- Name: user_type user_type_name_key; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.user_type
    ADD CONSTRAINT user_type_name_key UNIQUE (name);


--
-- Name: user_type user_type_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.user_type
    ADD CONSTRAINT user_type_pkey PRIMARY KEY (id);


--
-- Name: attachment_parent_idx; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX attachment_parent_idx ON public.attachment USING btree (parent_attachment_id);


--
-- Name: execution_run_version_unique; Type: INDEX; Schema: public; Owner: admin
--

CREATE UNIQUE INDEX execution_run_version_unique ON public.execution USING btree (run_id, test_case_version_id);


--
-- Name: resolution_hw_unique; Type: INDEX; Schema: public; Owner: admin
--

CREATE UNIQUE INDEX resolution_hw_unique ON public.resolution USING btree (h, w);


--
-- Name: test_case_version_unique; Type: INDEX; Schema: public; Owner: admin
--

CREATE UNIQUE INDEX test_case_version_unique ON public.test_case_version USING btree (test_case_id, version);


--
-- Name: user_email_unique; Type: INDEX; Schema: public; Owner: admin
--

CREATE UNIQUE INDEX user_email_unique ON public."user" USING btree (email);


--
-- Name: attachment attachment_parent_fk; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.attachment
    ADD CONSTRAINT attachment_parent_fk FOREIGN KEY (parent_attachment_id) REFERENCES public.attachment(id);


--
-- Name: attachment attachment_resolution_fk; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.attachment
    ADD CONSTRAINT attachment_resolution_fk FOREIGN KEY (resolution_id) REFERENCES public.resolution(id);


--
-- Name: attachment attachment_user_fk; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.attachment
    ADD CONSTRAINT attachment_user_fk FOREIGN KEY (uploaded_by) REFERENCES public."user"(id);


--
-- Name: device device_project_fk; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.device
    ADD CONSTRAINT device_project_fk FOREIGN KEY (project_id) REFERENCES public.project(id);


--
-- Name: execution execution_attachment_fk; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.execution
    ADD CONSTRAINT execution_attachment_fk FOREIGN KEY (attachment_id) REFERENCES public.attachment(id);


--
-- Name: execution execution_device_fk; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.execution
    ADD CONSTRAINT execution_device_fk FOREIGN KEY (device_id) REFERENCES public.device(id);


--
-- Name: execution execution_run_fk; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.execution
    ADD CONSTRAINT execution_run_fk FOREIGN KEY (run_id) REFERENCES public.run(id);


--
-- Name: execution execution_status_fk; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.execution
    ADD CONSTRAINT execution_status_fk FOREIGN KEY (status_id) REFERENCES public.status(id);


--
-- Name: execution execution_tcv_fk; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.execution
    ADD CONSTRAINT execution_tcv_fk FOREIGN KEY (test_case_version_id) REFERENCES public.test_case_version(id);


--
-- Name: execution execution_user_fk; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.execution
    ADD CONSTRAINT execution_user_fk FOREIGN KEY (executed_by) REFERENCES public."user"(id);


--
-- Name: project project_client_fk; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.project
    ADD CONSTRAINT project_client_fk FOREIGN KEY (client_id) REFERENCES public.client(id);


--
-- Name: run run_project_fk; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.run
    ADD CONSTRAINT run_project_fk FOREIGN KEY (project_id) REFERENCES public.project(id);


--
-- Name: status status_status_set_fk; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.status
    ADD CONSTRAINT status_status_set_fk FOREIGN KEY (status_set_id) REFERENCES public.status_set(id);


--
-- Name: suitcase suitcase_test_case_fk; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.suitcase
    ADD CONSTRAINT suitcase_test_case_fk FOREIGN KEY (test_case_id) REFERENCES public.test_case(id);


--
-- Name: suitcase suitcase_test_suite_fk; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.suitcase
    ADD CONSTRAINT suitcase_test_suite_fk FOREIGN KEY (test_suite_id) REFERENCES public.test_suite(id);


--
-- Name: test_case_version tcv_created_by_fk; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.test_case_version
    ADD CONSTRAINT tcv_created_by_fk FOREIGN KEY (created_by) REFERENCES public."user"(id);


--
-- Name: test_case_version tcv_test_case_fk; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.test_case_version
    ADD CONSTRAINT tcv_test_case_fk FOREIGN KEY (test_case_id) REFERENCES public.test_case(id);


--
-- Name: test_case test_case_scenario_fk; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.test_case
    ADD CONSTRAINT test_case_scenario_fk FOREIGN KEY (scenario_id) REFERENCES public.scenario(id);


--
-- Name: test_case test_case_status_set_fk; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.test_case
    ADD CONSTRAINT test_case_status_set_fk FOREIGN KEY (status_set_id) REFERENCES public.status_set(id);


--
-- Name: user_group user_group_created_by_fk; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.user_group
    ADD CONSTRAINT user_group_created_by_fk FOREIGN KEY (created_by_id) REFERENCES public."user"(id);


--
-- Name: user_group user_group_owner_fk; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.user_group
    ADD CONSTRAINT user_group_owner_fk FOREIGN KEY (owner_id) REFERENCES public."user"(id);


--
-- Name: user user_user_group_fk; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_user_group_fk FOREIGN KEY (user_group_id) REFERENCES public.user_group(id);


--
-- Name: user user_user_type_fk; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_user_type_fk FOREIGN KEY (user_type_id) REFERENCES public.user_type(id);


--
-- PostgreSQL database dump complete
--

\unrestrict QUy3rPIJKXtL2HsMDmfOHSg0HP8f1es6C7XQNII0PCrjXH7X9syo09cpSNQJhep

