CREATE TABLE IF NOT EXISTS "resolution" (
  "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "h" INTEGER NOT NULL,
  "w" INTEGER NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS resolution_hw_unique ON "resolution" ("h", "w");

CREATE TABLE IF NOT EXISTS "client" (
  "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "name" VARCHAR
);

CREATE TABLE IF NOT EXISTS "user_type" (
  "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "name" VARCHAR UNIQUE NOT NULL,
  "description" TEXT
);

INSERT INTO "user_type" (name, description)
VALUES
  ('regular', 'Default regular user'),
  ('admin', 'Administrator')
ON CONFLICT (name)
DO UPDATE SET description = EXCLUDED.description;


CREATE TABLE IF NOT EXISTS "status_set" (
  "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "name" VARCHAR UNIQUE
);

CREATE TABLE IF NOT EXISTS "status" (
  "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "status_set_id" INTEGER NOT NULL,
  "name" VARCHAR NOT NULL,
  "description" TEXT
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'status_status_set_fk'
  ) THEN
    ALTER TABLE "status"
      ADD CONSTRAINT status_status_set_fk
      FOREIGN KEY ("status_set_id") REFERENCES "status_set" ("id");
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS "scenario" (
  "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "name" VARCHAR UNIQUE
);

CREATE TABLE IF NOT EXISTS "test_suite" (
  "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "name" VARCHAR UNIQUE
);

CREATE TABLE IF NOT EXISTS "project" (
  "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "name" VARCHAR,
  "client_id" INTEGER NOT NULL
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'project_client_fk'
  ) THEN
    ALTER TABLE "project"
      ADD CONSTRAINT project_client_fk
      FOREIGN KEY ("client_id") REFERENCES "client" ("id");
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS "device" (
  "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "project_id" INTEGER NOT NULL,
  "name_external" VARCHAR,
  "name_internal" VARCHAR,
  "cpu" VARCHAR,
  "gpu" VARCHAR,
  "ram" VARCHAR
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'device_project_fk'
  ) THEN
    ALTER TABLE "device"
      ADD CONSTRAINT device_project_fk
      FOREIGN KEY ("project_id") REFERENCES "project" ("id");
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS "user_group" (
  "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "created_by_id" INTEGER NOT NULL,
  "owner_id" INTEGER NOT NULL,
  "name" VARCHAR UNIQUE
);

CREATE TABLE IF NOT EXISTS "user" (
  "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "user_group_id" INTEGER,
  "user_type_id" INTEGER NOT NULL,
  "first_name" VARCHAR NOT NULL,
  "last_name" VARCHAR NOT NULL,
  "email" VARCHAR NOT NULL,
  "password" VARCHAR NOT NULL,
  "active" BOOLEAN DEFAULT TRUE,
  "created_at" TIMESTAMP DEFAULT now(),
  "last_login_at" TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS user_email_unique ON "user" ("email");

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'user_user_type_fk'
  ) THEN
    ALTER TABLE "user"
      ADD CONSTRAINT user_user_type_fk
      FOREIGN KEY ("user_type_id") REFERENCES "user_type" ("id");
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'user_user_group_fk'
  ) THEN
    ALTER TABLE "user"
      ADD CONSTRAINT user_user_group_fk
      FOREIGN KEY ("user_group_id") REFERENCES "user_group" ("id");
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'user_group_created_by_fk'
  ) THEN
    ALTER TABLE "user_group"
      ADD CONSTRAINT user_group_created_by_fk
      FOREIGN KEY ("created_by_id") REFERENCES "user" ("id");
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'user_group_owner_fk'
  ) THEN
    ALTER TABLE "user_group"
      ADD CONSTRAINT user_group_owner_fk
      FOREIGN KEY ("owner_id") REFERENCES "user" ("id");
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS "test_case" (
  "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "scenario_id" INTEGER NOT NULL,
  "status_set_id" INTEGER NOT NULL
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'test_case_scenario_fk'
  ) THEN
    ALTER TABLE "test_case"
      ADD CONSTRAINT test_case_scenario_fk
      FOREIGN KEY ("scenario_id") REFERENCES "scenario" ("id");
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'test_case_status_set_fk'
  ) THEN
    ALTER TABLE "test_case"
      ADD CONSTRAINT test_case_status_set_fk
      FOREIGN KEY ("status_set_id") REFERENCES "status_set" ("id");
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS "test_case_version" (
  "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "test_case_id" INTEGER NOT NULL,
  "created_by" INTEGER NOT NULL,
  "release_ready" BOOLEAN DEFAULT FALSE,
  "version" INTEGER NOT NULL,
  "name" VARCHAR,
  "description" TEXT,
  "steps" TEXT,
  "expected_result" TEXT,
  "created_at" TIMESTAMP DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS test_case_version_unique
  ON "test_case_version" ("test_case_id", "version");

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'tcv_test_case_fk'
  ) THEN
    ALTER TABLE "test_case_version"
      ADD CONSTRAINT tcv_test_case_fk
      FOREIGN KEY ("test_case_id") REFERENCES "test_case" ("id");
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'tcv_created_by_fk'
  ) THEN
    ALTER TABLE "test_case_version"
      ADD CONSTRAINT tcv_created_by_fk
      FOREIGN KEY ("created_by") REFERENCES "user" ("id");
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS "suitcase" (
  "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "test_case_id" INTEGER NOT NULL,
  "test_suite_id" INTEGER NOT NULL
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'suitcase_test_case_fk'
  ) THEN
    ALTER TABLE "suitcase"
      ADD CONSTRAINT suitcase_test_case_fk
      FOREIGN KEY ("test_case_id") REFERENCES "test_case" ("id");
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'suitcase_test_suite_fk'
  ) THEN
    ALTER TABLE "suitcase"
      ADD CONSTRAINT suitcase_test_suite_fk
      FOREIGN KEY ("test_suite_id") REFERENCES "test_suite" ("id");
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS "run" (
  "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "name" VARCHAR,
  "started_at" TIMESTAMP,
  "done_at" TIMESTAMP,
  "test_suite_metadata" TEXT,
  "project_id" INTEGER NOT NULL
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'run_project_fk'
  ) THEN
    ALTER TABLE "run"
      ADD CONSTRAINT run_project_fk
      FOREIGN KEY ("project_id") REFERENCES "project" ("id");
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS "attachment" (
  "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "parent_attachment_id" INTEGER,
  "uploaded_by" INTEGER NOT NULL,
  "resolution_id" INTEGER,
  "filename" VARCHAR,
  "relative_path" VARCHAR,
  "uploaded_at" TIMESTAMP DEFAULT now(),
  "presentmon_file" BOOLEAN,
  "presentmon_version" VARCHAR,
  "settings" JSON
);

CREATE INDEX IF NOT EXISTS attachment_parent_idx
  ON "attachment" ("parent_attachment_id");

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'attachment_user_fk'
  ) THEN
    ALTER TABLE "attachment"
      ADD CONSTRAINT attachment_user_fk
      FOREIGN KEY ("uploaded_by") REFERENCES "user" ("id");
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'attachment_resolution_fk'
  ) THEN
    ALTER TABLE "attachment"
      ADD CONSTRAINT attachment_resolution_fk
      FOREIGN KEY ("resolution_id") REFERENCES "resolution" ("id");
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'attachment_parent_fk'
  ) THEN
    ALTER TABLE "attachment"
      ADD CONSTRAINT attachment_parent_fk
      FOREIGN KEY ("parent_attachment_id") REFERENCES "attachment" ("id");
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS "execution" (
  "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "device_id" INTEGER NOT NULL,
  "run_id" INTEGER NOT NULL,
  "test_case_version_id" INTEGER NOT NULL,
  "executed_by" INTEGER NOT NULL,
  "status_id" INTEGER NOT NULL,
  "attachment_id" INTEGER,
  "actual_result" TEXT,
  "executed_at" TIMESTAMP,
  "execution_order" INTEGER NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS execution_run_version_unique
  ON "execution" ("run_id", "test_case_version_id");

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'execution_run_fk') THEN
    ALTER TABLE "execution"
      ADD CONSTRAINT execution_run_fk
      FOREIGN KEY ("run_id") REFERENCES "run" ("id");
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'execution_tcv_fk') THEN
    ALTER TABLE "execution"
      ADD CONSTRAINT execution_tcv_fk
      FOREIGN KEY ("test_case_version_id") REFERENCES "test_case_version" ("id");
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'execution_status_fk') THEN
    ALTER TABLE "execution"
      ADD CONSTRAINT execution_status_fk
      FOREIGN KEY ("status_id") REFERENCES "status" ("id");
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'execution_user_fk') THEN
    ALTER TABLE "execution"
      ADD CONSTRAINT execution_user_fk
      FOREIGN KEY ("executed_by") REFERENCES "user" ("id");
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'execution_device_fk') THEN
    ALTER TABLE "execution"
      ADD CONSTRAINT execution_device_fk
      FOREIGN KEY ("device_id") REFERENCES "device" ("id");
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'execution_attachment_fk') THEN
    ALTER TABLE "execution"
      ADD CONSTRAINT execution_attachment_fk
      FOREIGN KEY ("attachment_id") REFERENCES "attachment" ("id");
  END IF;
END $$;
